# Generated by Django 4.1.2 on 2022-10-05 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=150)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('date_of_birth', models.DateTimeField()),
                ('employment_start_date', models.DateTimeField(blank=True, null=True)),
                ('employment_end_date', models.DateTimeField(blank=True, null=True)),
                ('last_birthday_notified', models.DateField(blank=True, null=True)),
                ('last_notification', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
