# Generated by Django 4.1.2 on 2022-10-05 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_employess_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employess',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
